language: python
# We use the built-in tox matrix capabilities instead of matrixing on different
# python versions directly.
python: 
  - 2.7
install:
  - pip install tox
script:
  - tox
env:
  - TOXENV=py27
  - TOXENV=py34
