[tox]
envlist = pre-commit, py38, py310, py311, py312, mypy
requires =
    virtualenv>=20.17

[flake8]
# TODO: fix long lines
max-line-length = 2000
ignore = E203
exclude = docs/*

[testenv]
deps=
    pytest
    py38: mock==1.0.0
commands=
    py.test {posargs:tests}


[testenv:mypy]
basepython=python3.8
deps = mypy
commands =
    mypy pysensu_yelp

[testenv:pre-commit]
basepython = python3.8
deps = pre-commit
commands =
    pre-commit install -f --install-hooks
    pre-commit run --all-files {posargs}
